// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chmlqbarvfbotkmockhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNobWxxYmFydmZib3RrbW9ja2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDkwODMsImV4cCI6MjA3MzA4NTA4M30.aNY1Mv3mBnecQ5AoloGhxXr16Qijj6JydRi5YpOcjOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});